package com.saab.tools.finance.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.saab.tools.finance.model.converter.TimestampLocalDateTimeConverter;
import lombok.*;

import java.time.LocalDateTime;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName="REPLACED_BY_ENVIRONMENT_VARIABLE")
@ToString
public class Sms {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="id")
    private String id;

    @DynamoDBAttribute(attributeName="date")
    @DynamoDBTypeConverted(converter = TimestampLocalDateTimeConverter.class)
    private LocalDateTime date;

    @DynamoDBAttribute(attributeName="message")
    private String message;

    @DynamoDBAttribute(attributeName="number")
    private String number;

    @DynamoDBAttribute(attributeName="createdAt")
    private String createdAt;

    @DynamoDBAttribute(attributeName="updatedAt")
    private String updatedAt;

    @DynamoDBAttribute(attributeName="generateTransaction")
    private boolean generateTransaction;

}
