package com.saab.tools.finance.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.saab.tools.finance.model.converter.LocalDateTimeConverter;
import com.saab.tools.finance.model.converter.LocalDateTimeJsonDeserializer;
import lombok.*;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import java.time.LocalDateTime;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName="Sms")
public class SMSNotification {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="id")
    private String id;

    @JsonDeserialize(using = LocalDateTimeJsonDeserializer.class)
    @DynamoDBAttribute(attributeName="date")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime date;

    @DynamoDBAttribute(attributeName="number")
    private String number;

    @DynamoDBAttribute(attributeName="message")
    private String message;

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.DEFAULT_STYLE, true, true);
    }
}
