package com.saab.tools.finance.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.saab.tools.finance.model.converter.LocalDateTimeConverter;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
  {
    "id": "1",
    "date": "2020-03-14T18:57:08.295165900",
    "category": "Mercado",
    "description": "Pick'n Pay",
    "value": 128.62,
    "type": "EXPENSE"
  }
 */
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName="FinanceTransaction")
public class Transaction {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="id")
    private String id;

    @DynamoDBAttribute(attributeName="date")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime date;

    @DynamoDBAttribute(attributeName="category")
    private String category;

    @DynamoDBAttribute(attributeName="description")
    private String description;

    @DynamoDBAttribute(attributeName="value")
    private BigDecimal value;

    @DynamoDBAttribute(attributeName="type")
    private String type; // EXPENSE or INCOME

}
