package com.saab.tools.finance.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.saab.tools.finance.model.converter.LocalDateTimeConverter;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName="REPLACED_BY_ENVIRONMENT_VARIABLE")
@ToString
public class Transaction {

    public static final String TYPE_EXPENSE = "EXPENSE";
    public static final String TYPE_INCOME = "INCOME";

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="id")
    private String id;

    @DynamoDBAttribute(attributeName="date")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime date;

    @DynamoDBAttribute(attributeName="category")
    private String category;

    @DynamoDBAttribute(attributeName="description")
    private String description;

    @DynamoDBAttribute(attributeName="value")
    private BigDecimal value;

    @DynamoDBAttribute(attributeName="type")
    private String type; // EXPENSE or INCOME

    @DynamoDBAttribute(attributeName="reversed")
    private boolean reversed;

    @DynamoDBAttribute(attributeName="reversedDate")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime reversedDate;

    @DynamoDBAttribute(attributeName="smsId")
    private String smsId;

}
